version: 0.0
os: linux
files:
  - source: /target/myapp.war
    destination: /opt/tomcat/webapps/
permissions:
  - object: /opt/tomcat/webapps/myapp.war
    pattern: "**"
    owner: tomcat
    group: tomcat
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  AfterInstall:
    - location: scripts/start_tomcat.sh
      runas: root
  ApplicationStart:
    - location: scripts/verify_application.sh
      runas: tomcat
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
